variable "lambda_consumer_function_name" {}
variable "lambda_consumer_role_name" {}
variable "lambda_consumer_policy_name" {}
variable "lambda_consumer_kinesis_batch_size" {}
variable "lambda_consumer_kinesis_retries" {}
variable "lambda_consumer_kinesis_window_secs" {}
variable "lambda_get_coordinates_function_name" {}
variable "lambda_get_coordinates_role_name" {}
variable "lambda_get_coordinates_policy_name" {}
variable "dynamodb_table_name" {}
variable "dynamodb_table_arn" {}
variable "dynamodb_ttl_seconds" {}
variable "dynamodb_ttl_field_name" {}
variable "kinesis_arn" {}
variable "lambda_consumer_source_dir" {}
variable "lambda_consumer_output_path" {}
variable "lambda_get_coordinates_source_dir" {}
variable "lambda_get_coordinates_output_path" {}
variable "s3_bucket_prefix" {}
variable "s3_lambda_consumer_key" {}
variable "s3_lambda_get_coordinates_key" {}